name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - dev
      - uat
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set environment parameters
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            ENV="dev"
          elif [ "${{ github.ref }}" == "refs/heads/uat" ]; then
            ENV="uat"
          elif [ "${{ github.ref }}" == "refs/heads/master" ]; then
            ENV="prod"
          else
            echo "Unsupported branch. Exiting."
            exit 1
          fi
          echo "ENVIRONMENT=${ENV}" >> $GITHUB_ENV

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file templates/eventbridge.yaml \
            --stack-name eventbridge-stack-${{ env.ENVIRONMENT }} \
            --parameter-overrides file://parameters/${{ env.ENVIRONMENT }}.json \
            --capabilities CAPABILITY_NAMED_IAM
