name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - dev
      - prod
      - uat  # Adicione outras branches conforme necessário

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}  # Use secrets se a variável não estiver configurada

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set environment parameters file
        run: |
          # Extrai o nome da branch e define o caminho do arquivo de parâmetros
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}")
          PARAM_FILE="parameters/${BRANCH_NAME}.json"
          echo "Using parameter file: ${PARAM_FILE}"

          # Verifica se o arquivo existe
          if [ ! -f "$PARAM_FILE" ]; then
            echo "Error: Parameter file ${PARAM_FILE} not found."
            exit 1
          fi

          echo "PARAM_FILE=${PARAM_FILE}" >> $GITHUB_ENV

      - name: Convert JSON to Parameter Overrides Format
        id: convert_params
        run: |
          echo "Reading parameters from file: ${PARAM_FILE}"
          cat "${PARAM_FILE}"  # Mostra o conteúdo do arquivo para depuração

          # Converte o JSON para uma lista de pares "ParameterKey=ParameterValue"
          PARAMS=$(jq -r "to_entries | map(\"\\(.key)=\\('\(.value|tostring)\\')\") | join(\" \")" "${PARAM_FILE}")

          if [ -z "$PARAMS" ]; then
            echo "Error: No parameters found or jq conversion failed."
            exit 1
          fi

          echo "Converted parameters: $PARAMS"
          echo "parameter_overrides=$PARAMS" >> $GITHUB_ENV

      - name: Deploy CloudFormation stack
        run: |
          echo "Starting CloudFormation deploy..."
          echo "Using parameters: ${{ env.parameter_overrides }}"
          aws cloudformation deploy \
            --template-file templates/eventbridge.yaml \
            --stack-name eventbridge-stack-${BRANCH_NAME} \
            --parameter-overrides ${{ env.parameter_overrides }} \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Debug environment
        run: env
